export interface MunicipalLeader {
  province: string;
  municipality: string;
  leaderName: string;
  office: string;
  aliases: string[];
}

function withOfficeAliases(aliases: string[], municipality: string): string[] {
  return [
    ...aliases,
    "Office of the Mayor",
    "Office of the Executive Mayor",
    municipality,
    `${municipality} municipality`,
    `${municipality} local municipality`,
    `${municipality} metro`,
    `${municipality} metropolitan municipality`,
    `${municipality} administration`,
    `${municipality} mayor`,
    `${municipality} executive mayor`,
    `mayoral committee ${municipality}`,
    `${municipality} mayoral office`,
  ];
}

// Verified against official municipal pages, municipal notices, or official municipal newsletters on 2026-03-16.
export const MUNICIPAL_LEADERS: MunicipalLeader[] = [
  {
    province: "Gauteng",
    municipality: "City of Johannesburg",
    leaderName: "Sello Morero",
    office: "Office of the Executive Mayor",
    aliases: withOfficeAliases(
      [
        "Sello Morero",
        "Morero",
        "Executive Mayor Sello Morero",
        "Mayor Sello Morero",
        "Joburg Mayor",
        "Johannesburg Mayor",
        "City of Johannesburg Mayor",
        "Executive Mayor of Johannesburg",
      ],
      "City of Johannesburg",
    ),
  },
  {
    province: "Gauteng",
    municipality: "City of Tshwane",
    leaderName: "Nasiphi Moya",
    office: "Office of the Executive Mayor",
    aliases: withOfficeAliases(
      [
        "Nasiphi Moya",
        "Dr Nasiphi Moya",
        "Mayor Nasiphi Moya",
        "Tshwane Mayor",
        "City of Tshwane Mayor",
        "Executive Mayor of Tshwane",
        "Tshwane metro",
        "City of Tshwane metro",
      ],
      "City of Tshwane",
    ),
  },
  {
    province: "Gauteng",
    municipality: "Ekurhuleni",
    leaderName: "Nkosindiphile Xhakaza",
    office: "Office of the Executive Mayor",
    aliases: withOfficeAliases(
      [
        "Nkosindiphile Xhakaza",
        "Xhakaza",
        "Mayor Xhakaza",
        "Ekurhuleni Mayor",
        "Executive Mayor of Ekurhuleni",
        "Ekurhuleni metro",
        "Ekurhuleni metropolitan municipality",
      ],
      "Ekurhuleni",
    ),
  },
  {
    province: "Gauteng",
    municipality: "Emfuleni",
    leaderName: "Sipho Radebe",
    office: "Office of the Executive Mayor",
    aliases: withOfficeAliases(
      [
        "Sipho Radebe",
        "Radebe",
        "Mayor Radebe",
        "Emfuleni Mayor",
        "Executive Mayor of Emfuleni",
        "Emfuleni municipality",
        "Emfuleni local municipality",
      ],
      "Emfuleni",
    ),
  },
  {
    province: "Western Cape",
    municipality: "City of Cape Town",
    leaderName: "Geordin Hill-Lewis",
    office: "Office of the Executive Mayor",
    aliases: withOfficeAliases(
      [
        "Geordin Hill-Lewis",
        "Geordin Gwyn Hill-Lewis",
        "Executive Mayor Geordin Gwyn Hill-Lewis",
        "Hill-Lewis",
        "Mayor Hill-Lewis",
        "Mayor Geordin Hill-Lewis",
        "Cape Town Mayor",
        "City of Cape Town Mayor",
        "Executive Mayor of Cape Town",
        "City of Cape Town metro",
        "Cape Town metro",
      ],
      "City of Cape Town",
    ),
  },
  {
    province: "KwaZulu-Natal",
    municipality: "eThekwini",
    leaderName: "Cyril Xaba",
    office: "Office of the Mayor",
    aliases: withOfficeAliases(
      [
        "Cyril Xaba",
        "Xaba",
        "Mayor Xaba",
        "eThekwini Mayor",
        "Durban Mayor",
        "Mayor of eThekwini",
        "eThekwini municipality",
        "eThekwini metro",
        "Durban metro",
      ],
      "eThekwini",
    ),
  },
  {
    province: "KwaZulu-Natal",
    municipality: "Msunduzi",
    leaderName: "Mzimkhulu Thebolla",
    office: "Office of the Mayor",
    aliases: withOfficeAliases(
      [
        "Mzimkhulu Thebolla",
        "Thebolla",
        "Mayor Thebolla",
        "Msunduzi Mayor",
        "Pietermaritzburg Mayor",
        "Mayor of Msunduzi",
        "Msunduzi municipality",
        "Msunduzi local municipality",
      ],
      "Msunduzi",
    ),
  },
  {
    province: "Eastern Cape",
    municipality: "Buffalo City",
    leaderName: "Princess Faku",
    office: "Office of the Executive Mayor",
    aliases: withOfficeAliases(
      [
        "Princess Faku",
        "Executive Mayor Princess Faku",
        "Faku",
        "Mayor Faku",
        "Mayor Princess Faku",
        "Buffalo City Mayor",
        "Executive Mayor of Buffalo City",
        "East London Mayor",
        "Buffalo City metro",
        "Buffalo City metropolitan municipality",
      ],
      "Buffalo City",
    ),
  },
  {
    province: "Limpopo",
    municipality: "Polokwane",
    leaderName: "Makoro John Mpe",
    office: "Office of the Executive Mayor",
    aliases: withOfficeAliases(
      [
        "Makoro John Mpe",
        "John Mpe",
        "Mpe",
        "Mayor Mpe",
        "Polokwane Mayor",
        "Executive Mayor of Polokwane",
        "Polokwane municipality",
        "Polokwane local municipality",
      ],
      "Polokwane",
    ),
  },
  {
    province: "Mpumalanga",
    municipality: "Mbombela",
    leaderName: "Sibongile Makushe-Mazibuko",
    office: "Office of the Executive Mayor",
    aliases: withOfficeAliases(
      [
        "Sibongile Makushe-Mazibuko",
        "Executive Mayor Sibongile Makushe-Mazibuko",
        "S.E. Makushe",
        "Makushe",
        "Mayor Makushe",
        "Mayor Sibongile Makushe-Mazibuko",
        "Mbombela Mayor",
        "Executive Mayor of Mbombela",
        "City of Mbombela",
        "Mbombela municipality",
      ],
      "Mbombela",
    ),
  },
  {
    province: "Mpumalanga",
    municipality: "Thembisile Hani",
    leaderName: "Lesetja Jacob Dikgale",
    office: "Office of the Executive Mayor",
    aliases: withOfficeAliases(
      [
        "Lesetja Jacob Dikgale",
        "Dikgale",
        "Mayor Dikgale",
        "Thembisile Hani Mayor",
        "Executive Mayor of Thembisile Hani",
        "Thembisile Hani municipality",
        "Thembisile Hani local municipality",
      ],
      "Thembisile Hani",
    ),
  },
  {
    province: "Northern Cape",
    municipality: "Sol Plaatje",
    leaderName: "Martha Bartlett",
    office: "Office of the Executive Mayor",
    aliases: withOfficeAliases(
      [
        "Martha Bartlett",
        "Executive Mayor Martha Bartlett",
        "Bartlett",
        "Mayor Bartlett",
        "Mayor Martha Bartlett",
        "Sol Plaatje Mayor",
        "Kimberley Mayor",
        "Executive Mayor of Sol Plaatje",
        "Sol Plaatje municipality",
        "Sol Plaatje executive mayor",
      ],
      "Sol Plaatje",
    ),
  },
  {
    province: "Free State",
    municipality: "Mangaung",
    leaderName: "Greg Nthatisi",
    office: "Office of the Executive Mayor",
    aliases: withOfficeAliases(
      [
        "Greg Nthatisi",
        "Nthatisi",
        "Mayor Nthatisi",
        "Mangaung Mayor",
        "Executive Mayor of Mangaung",
        "Mangaung Metro",
        "Mangaung Metropolitan Municipality",
        "Bloemfontein Mayor",
      ],
      "Mangaung",
    ),
  },
];
